### PR TITLE
adding bscfee.wtf to traders section

### PR DESCRIPTION
**Pull request by pujux**
hey there! I built https://bscfee.wtf and would like you to add it to your traders section so people can use it and see how much BNB they spent on transaction sent over the binance smart chain! 👍🏻  feedback is well appreciated!

thanks!

### CODE REVIEW

**Review by stillnoob200 — CHANGES_REQUESTED** [review]
Hi, i appreaciate your change into the Wiki. If you mind, you could change the ETH mainnet and Matic Mainnet average fee on line 29 and 32. Currently, ETH mainnet contract transaction costs between $20-$60 per transaction while Matic network contract transaction costs around $0.0047 per transaction. I don't know about the fees on BSC since i never touch them but when i try to find some articles on Google most transactions cost around $0.2-$0.3 per transaction and your wiki file written as $0.02 as average fee of BSC Mainnet, i don't know if it is mistyped or miscalculationed or other reason so if you mind, could you change the BSC average fee into the right one? Maybe you can also sort the table starting from the highest fee into the lowest fee.

**Comment by pujux** [comment]
Sure, will do tomorrow, really busy today! Thanks for your reply! 👍🏻

**Comment by pujux** [comment]
Totally forgot about this in my hurry... 

Just checked Matic Network and it costs 0.000021 MATIC / Transaction which is 0.00004$.
Ethereum transaction fee is pretty random right now apparently (0,00044 ETH (1.15$) on MetaMask but 0,008 ETH (nearly 20$) on Binance)
BSC is around 0.000105 BNB per transaction, thats around 0,03-0,04$.

Do you want me to update the values accordingly?

**Comment by stillnoob200** [comment]
Yes. By the way, don't follow any binance withdrawal fee. The fee is not only the network fee but also the service fee from binance

**Comment by pujux** [comment]
I just updated all the values and added my sources for it. 
xDai was pretty incorrect apparently since it has a fixed 1 GWEI transaction fee which corresponds to 0,000000001$ since xDai is stable at 1$.

**Comment by lkngtn** [comment]
We no longer have this section in the wiki, so closing for now, if we re-add a fee comparison between networks we can revisit.

**Pull request closed without merging**
