### PR TITLE
Change the onboarding message to the commands

### PR DESCRIPTION
**Pull request by hernandoagf**
Changed pollen old onboarding message to the new bot commands.

image

### CODE REVIEW

**Review by stillnoob200 — APPROVED** [review]

**Review by befitsandpiper — APPROVED** [review]

**Comment by onbjerg** [comment]
@befitsandpiper I assume that this information is accurate since you approved it - is there any reason it has not been merged yet (e.g. are we waiting for something to be released)? Otherwise I'm going to go ahead and merge it :)

**Comment by stillnoob200** [comment]
I wonder if it is possible to make the video guide embedded in the wiki but currently no one intend to do the video for now. But if someone intends to do the video guide in the near future then let's wait a little bit.

**Comment by onbjerg** [comment]
[That is a possibility](https://docs.gitbook.com/editing-content/embeds)

**Comment by hernandoagf** [comment]
Updated the Pollen wiki entry with the new pollen onboarding flow.

- Save wallet command is required and also saves discord information.
- No required save-discord command anymore.

**Review by stillnoob200 — APPROVED** [review]

**Review by lkngtn — APPROVED** [review]

**Pull request merged**
